version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=mongodb://mongo:27017/swstarter
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/starwars
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
